
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--no-audit --no-fund"

# Use the official Next.js plugin for proper routing/SSR
[[plugins]]
  package = "@netlify/plugin-nextjs"
